ABE/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ABE.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('User.urls', namespace='user')),
)

User/urls.py
from django.conf.urls import patterns, url
from User.views import *

urlpatterns = patterns('',
                       url('^login', Login, name="login"),
                       url('^register/$', Register, name="register"),
                       url('^change_password', change_password, name="change_password"),
                       url('^logout/$', Logout, name="logout"),
                       url('^index', index, name="index"),
                       url('^upload/$', upload_file, name="upload"),
                       url('^download/$', download_file, name="download"),
                       url('^download_file/?file=(?P<file_id>\d+)/$', file_down_single, name="file_down_single"),
                       url('^delete_file/?file=(?P<file_id>\d+)/$', file_delete, name="file_delete"),
                       url('^delete_message/$', delete_message, name="delete_message"),
                       url('^share/$', share_file, name='share'),
                       url('^list/$', list_file, name='list'),
                       url('^file?.*/$', upload, name="test"),
                       url('^test_upload/$', test_upload, name="test_upload"),
                       url('^get_department/$', get_department, name="get_department"),
                       url('^improve_user_info/$', improve_user_info, name='improve_user_info'),
                       url('^get_department_multiple/$', get_department_multiple, name="get_department_multiple"),
                       url('^message_list/$', message_list, name="message_list"),
                       url('^upload_new_message/$', upload_new_message, name='upload_new_message'),
                       url('^upload_new_inline_message', upload_new_inline_message, name='upload_new_inline_message'),
                       url('^user_info_if_complete_authenticate/$', user_info_if_complete_authenticate,
                           name='user_info_if_complete_authenticate'),
                       )

User/models.py
#coding=utf8
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
            password=password,
            username=username,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='邮箱',
        max_length=255,
        unique=True,
    )
    username = models.CharField(verbose_name="用户名", max_length=30, unique=True)
    date_of_birth = models.DateField(verbose_name="出生日期")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth', 'username']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    class Meta:
        verbose_name = "用户"
        verbose_name_plural = "用户"


def upload_file_path(instance, filename):
    import time
    import os
    path = "file/" + instance.user.username + time.strftime("/%Y/%m/%d/") + filename.split('/')[-1]
    print "model filename", filename
    print "model filepath", path
    print path
    print '/'.join(['content', instance.user.username, filename])
    # return '/'.join(['content', instance.user.username, filename])
    return path


class FileFromUser(models.Model):
    Share_Info = {
        ('1', '公开'),
        ('2', '可共享'),
        ('3', '私人')
    }
    user = models.ForeignKey(MyUser)
    file = models.FileField(upload_to=upload_file_path)
    share = models.CharField(max_length=400)
    key = models.CharField(max_length=200)
    date_upload = models.DateTimeField(auto_now_add=True)
    share_type = models.CharField(max_length=1, choices=Share_Info)

    def __unicode__(self):
        return self.file.name.split('/')[-1]

    def file_size_humanility(self):
        size = self.file.size
        if size <= 1000:
            return str(size) + u"bit"
        elif (size >= 1000) and (size <= 1000000):
            return str(round(size/1000.0, 2)) + u"KB"
        elif (size >= 1000000) and (size <= 1000000000):
            return str(round(size/1000000.0, 2)) + u"MB"
        elif (size >= 1000000000) and (size <= 1000000000000):
            return str(round(size/1000000000.0, 2)) + u"GB"
    class Meta:
        verbose_name = "文件"
        verbose_name_plural = "文件"


class Academy(models.Model):

    name = models.CharField(verbose_name="学院名称", max_length=100)

    class Meta:
        verbose_name = "学院"
        verbose_name_plural = "学院"

    def __unicode__(self):
        return self.name

class Department(models.Model):
    academy = models.ForeignKey(Academy)
    name = models.CharField(verbose_name="专业名称", max_length=100)

    class Meta:
        verbose_name = "系"
        verbose_name_plural = "系"

    def __unicode__(self):
        return self.name


class DataOfUser(models.Model):

    SexInfo = {
        ('1', '女'),
        ('2', '男'),
    }
    identityInfo = {
        ('4', '本科生'),
        ('5', '研究生'),
        ('6', '教师')
    }
    user = models.OneToOneField(MyUser)
    sex = models.CharField(verbose_name="性别", max_length=1, choices=SexInfo)
    academy = models.ForeignKey(Academy)
    major = models.ForeignKey(Department, verbose_name="所在系")
    identity = models.CharField(verbose_name="身份", max_length=1, choices=identityInfo)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = "用户信息"


class MessageList(models.Model):
    user = models.ForeignKey(MyUser)
    content = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    file_plug_in = models.ForeignKey(FileFromUser, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = "信息列表"
        verbose_name_plural = "信息列表"
        ordering = ['-date']


class MessageListInline(models.Model):
    messageList = models.ForeignKey(MessageList)
    content = models.CharField(max_length=125)
    user = models.ForeignKey(MyUser)
    user_pre = models.CharField(verbose_name="上一个用户", max_length=30, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = "回复信息"
        verbose_name_plural = "回复信息"
        ordering = ['-date']


class PostMessageTimeCheck(models.Model):
    user = models.ForeignKey(MyUser)
    time = models.DateTimeField()

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = "用户机器评论提交审核"
        verbose_name_plural = "用户机器评论提交审核"

User/forms.py
#coding=utf8
from django import forms
from django.forms import ModelForm
from User.models import FileFromUser


class UploadFileForm(forms.Form):

    title = forms.CharField(label="标题", max_length=50)
    file = forms.FileField(label="文件")


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.PasswordInput()

class UploadFileFormFromModel(ModelForm):
    class Meta:
        model = FileFromUser
        fields = ['file', 'share', 'share_type']

User/templates/User/download.html
{% extends 'User/index.html' %}
{% block title %}文件下载{% endblock %}
{% block intert-hook %}
    <div class="overview">
       <h1 class="page-header">文件下载</h1>
       <div class="container">
           <div class="row">
               <div class="col-xs-12 col-md-9">
                   <div class="my_file">
                       {% ifequal user_files.count 0 %}
                           <h3>用户暂时没有个人文件</h3>
                       {% else %}

                           <table class="my_file_table table table-striped">
                               <caption class="my_file_table_caption"><h3>我的文件</h3></caption>
                               <tr>
                                   <th>文件名</th>
                                   <th>大小</th>
                                   <th>上传日期</th>
                                   <th>共享</th>
                                   <th>操作</th>
                               </tr>
                               {% for file in user_files %}
                                <tr>
                                    <td>{{ file }}</td>
                                    <td>{{ file.file_size_humanility }}</td>
                                    <td>{{ file.date_upload }}</td>
                                    <td>{{ file.get_share_type_display }}</td>
                                    <td><a href="{% url 'user:file_down_single' file.id %}" target="_blank">下载</a><a href="{% url 'user:file_delete' file.id %}" target="_blank"> /删除</a></td>
                                </tr>
                                {% endfor %}
                           </table>
                       {% endifequal %}
                   </div>
                   <div class="other_file">

                   </div>
               </div>
           </div>
       </div>
    </div>
{% endblock %}

User/templates/User/list.html
{% extends 'User/index.html' %}
{% block title %}文件列表{% endblock %}
{% block intert-hook %}
    <div class="overview">
       <h1 class="page-header">文件列表</h1>
       <p>列表</p>
    </div>
{% endblock %}

User/templates/User/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    {# Load CSS and JavaScript #}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet"/>

    <title>用户登录</title>
</head>
<body>
    <div class="container">
        <form class="form-signin" method="post">
            {% csrf_token %}
            <h2 class="form-signin-heading">请登录</h2>
            <label for="id_email" class="sr-only">Email address</label>
            <input type="email" id="id_email" maxlength="255" name="email" class="form-control" placeholder="Email address" required autofocus>
            <label for="id_password" class="sr-only">Password</label>
            <input type="password" id="id_password" maxlength="128" name="password" class="form-control" placeholder="Password" required>
            <input type="hidden" name="next" value="{{ next }}" />
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
            <br/>
            <a href="{% url 'user:register' %}"><button class="btn btn-lg btn-info btn-block" type="button">注册</button></a>

      </form>
    </div>
{#    <div class="container">#}
{#        <form class="form-signin" method="post" class="form">#}
{#         <h2 class="form-signin-heading">请登录</h2>#}
{#          {% csrf_token %}#}
{#          {% bootstrap_form form %}#}
{#          {% buttons %}#}
{#            <button type="submit" class="btn btnbtn-lg btn-primary btn-block">#}
{#               登录#}
{#            </button>#}
{#          {% endbuttons %}#}
{#        </form>#}
{#    </div>#}
</body>
</html>

User/templates/User/message_inline_single.html
{% load static %}
<div id="message_inline_id_{{ message_inline.id }}">
   <div class="col-xs-3 col-sm-3 col-md-2 message-list-inline-head-img-field">
       <div class="head-img">
            <img src="{% static 'img/figure.png' %}"  class="img-thumbnail">
       </div>
   </div>
   <div class="col-xs-9 col-sm-8 col-md-9 message-list-inline-content">
       <div class="user">
           <p><span style="color: #428bca">{{ message_inline.user.username }} </span>
               {% if message_inline.user_pre %}
               回复 <span>{{ message_inline.user_pre }}</span>
               {% endif %}
           </p>
       </div>
       <div class="content">
           <div class="content-detail">
               <p>{{ message_inline.content }}</p>
           </div>
       </div>
       <div class="date-info">
           <p>
               <span>{{ message_inline.date }} 发布</span>
               <button class="btn btn-info btn-xs" id="btnInline {{ message_inline.messageList_id }} {{ message_inline.user.username }}" data-toggle="modal" data-target="#message_reply" onclick="get_inline_reply_info(this)">回复</button>
               {% if message_inline.user == user %}
                   <button class="btn btn-info btn-xs" id="btnInline {{ message_inline.id }}" onclick="delete_message(this)">删除</button>
               {% endif %}
           </p>
       </div>
   </div>
</div>

User/templates/User/message_single.html
{% load static %}
<div class="col-sm-12 col-md-9 message-list-single" id="message_id_{{ message.id }}">
   <div class="row">
       <div class="col-xs-3 col-sm-2 col-md-2 message-list-top-head-img">
           <div class="head-img">
               {% if message.file_plug_in %}
               <img src="{% static 'img/file.png' %}" class="img-thumbnail">
               {% else %}
               <img src="{% static 'img/figure.png' %}"  class="img-thumbnail">
               {% endif %}
           </div>
       </div>
       <div class="col-xs-9 col-sm-8 col-md-9 message-list-top-content">
           <div class="user">
               <p>
                   <span>{{ message.user.username }} </span>
                   {% if message.file_plug_in %}
                       分享了文件
                   {% else %}
                       发布了信息
                   {% endif %}

               </p>
           </div>
           <div class="content">
               <div class="content-detail">
                   <p>{{ message.content }}</p>
               </div>
           </div>
           <div class="file-plugin">
               {% if message.file_plug_in %}
                    <button class="btn btn-info btn-xs">
                        <a href="{% url 'user:file_down_single' message.file_plug_in.id %}" target="_blank">附件下载</a>
                        </button>
                            <span>
                                <a href="{% url 'user:file_down_single' message.file_plug_in.id %}" target="_blank">{{ message.file_plug_in }}</a>
                            </span>

               {% endif %}
           </div>
           <div class="date-info">
               <p>
                   <span>{{ message.date }} 发布</span>
                   <button class="btn btn-info btn-xs" id="btnTop {{ message.id }} {{ message.user.username }}" data-toggle="modal" onclick="get_inline_reply_info(this)" data-target="#message_reply">回复</button>
                   {% if message.user == user %}
                       <button class="btn btn-info btn-xs" id="btnTop {{ message.id }}" onclick="delete_message(this)">删除</button>
                   {% endif %}
               </p>
           </div>
       </div>
       <div class="col-xs-10 col-sm-10 col-md-10 col-xs-offset-1 col-sm-offset-1 col-md-offset-2">

           <div class="row message-list-inline">
           {% for message_inline in message.messagelistinline_set.all %}
               <div id="message_inline_id_{{ message_inline.id }}">
                   <div class="col-xs-3 col-sm-3 col-md-2 message-list-inline-head-img-field">
                       <div class="head-img">
                            <img src="{% static 'img/figure.png' %}"  class="img-thumbnail">
                       </div>
                   </div>
                   <div class="col-xs-9 col-sm-8 col-md-9 message-list-inline-content">
                       <div class="user">
                           <p><span style="color: #428bca">{{ message_inline.user.username }} </span>
                               {% if message_inline.user_pre %}
                               回复 <span>{{ message_inline.user_pre }}</span>
                               {% endif %}
                           </p>
                       </div>
                       <div class="content">
                           <div class="content-detail">
                               <p>{{ message_inline.content }}</p>
                           </div>
                       </div>
                       <div class="date-info">
                           <p>
                               <span>{{ message_inline.date }} 发布</span>
                               <button class="btn btn-info btn-xs" id="btnInline {{ message_inline.messageList_id }} {{ message_inline.user.username }}" data-toggle="modal" data-target="#message_reply" onclick="get_inline_reply_info(this)">回复</button>
                               {% if message.user == user %}
                                   <button class="btn btn-info btn-xs" id="btnInline {{ message_inline.id }}" onclick="delete_message(this)">删除</button>
                               {% endif %}
                           </p>
                       </div>
                   </div>
               </div>
               {% endfor %}
           </div>

       </div>
   </div>
</div>

User/templates/User/register.html
{# Load the tag library #}
{% load bootstrap3 %}
{% load staticfiles %}

{# Load CSS and JavaScript #}
<title>注册</title>
<link href="{% static 'css/login.css' %}" rel="stylesheet"/>
{#<script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>#}
{#<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />#}
{#<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />#}
{#<script type="text/javascript" src="/admin/jsi18n/"></script>#}
{#<script type="text/javascript" src="/static/admin/js/core.js"></script>#}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script>
{#    alert("请使用chrome firefox sarfri 等支持html5的新版本浏览器");#}
    $(document).ready(function(){
    $("#id_date_of_birth").removeAttr('type').attr('type', 'date');
});
</script>
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{# Display a form #}
<form class="form-signin" method="post" class="form">

      <h2>注册</h2>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary btn-lg btn-block">
          提交
        </button>
      {% endbuttons %}
{#    <h2>注册</h2>#}
{#        {% csrf_token %}#}
{#        <div class="form-group"><label class="control-label" for="id_email">邮箱</label><input class="form-control" id="id_email" maxlength="255" name="email" placeholder="邮箱" required="required" title="" type="email" /></div>#}
{#        <div class="form-group"><label class="control-label" for="id_username">用户名</label><input class="form-control" id="id_username" maxlength="30" name="username" placeholder="用户名" required="required" title="" type="text" /></div>#}
{#        <div class="form-group"><label class="control-label" for="id_date_of_birth">出生日期</label><input class="form-control vDateField" type="date" id="id_date_of_birth" name="date_of_birth" placeholder="出生日期" required="required" size="10" title="" type="text" /></div>#}
{#        <div class="form-group"><label class="control-label" for="id_password1">密码</label><input class="form-control" id="id_password1" name="password1" placeholder="密码" required="required" title="" type="password" /></div>#}
{#        <div class="form-group"><label class="control-label" for="id_password2">确认密码</label><input class="form-control" id="id_password2" name="password2" placeholder="确认密码" required="required" title="" type="password" /></div>#}
{#        <div class="form-group">#}
{#            <button type="submit" class="btn btn-primary btn-lg btn-block">#}
{#            提交#}
{#            </button>#}
{#        </div>#}
</form>

{# Read the documentation for more information #}

User/templates/User/test_upload.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
    <title>jQuery File Upload Example</title>
    {% load staticfiles %}
</head>
<body>
    <input id="fileupload" type="file" name="files[]" data-url="{% url 'user:test_upload' %}" multiple>
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Upload/js/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'Upload/js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'Upload/js/jquery.fileupload.js' %}"></script>
    <script>
    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            add: function (e, data) {
                data.context = $('<button/>').text('上传')
                    .appendTo(document.body)
                    .click(function () {
                        data.context = $('<p/>').text('上传中...').replaceAll($(this));
                        var jqXHR = data.submit()
                        .success(function (result, textStatus, jqXHR) {
                                    alert(result);
                                })
                        .error(function (jqXHR, textStatus, errorThrown) {/* ... */})
                        .complete(function (result, textStatus, jqXHR) {/* ... */});
                    });
            },

            done: function (e, data) {
                data.context.text('上传结束');
            }
        });
    });
    </script>
</body>
</html>

User/templates/User/upload.html
{% extends 'User/index.html' %}
{% block script %}
    <script>
        var file_share_dander_info = ["file_share_sex", "file_share_identity", "file_share_academy", "file_share_department"];
        function set_file_share_object(){
            var form = $("#file_upload_form");
            var share_type = $("#id_share_type").val();
            if (share_type == "2"){
                form.find("#file_upload_btn").attr('type', 'button');
                $("#fileAttributeSelect").removeAttr('hidden', 'hidden');
            }
            else if(share_type == '1'){
                $("#fileAttributeSelect").attr('hidden', 'hidden');
                $("#id_share").val("public");
                form.find("#file_upload_btn").attr('type', 'submit');
            }
            else if(share_type == '3'){
                $("#fileAttributeSelect").attr('hidden', 'hidden');
                $("#id_share").val("private");
                form.find("#file_upload_btn").attr('type', 'submit');
            }
        }
        function alert_complete_user_info(obj){
            console.log($(obj).attr('class'));
            if ($(obj).attr('type') == 'button') {
                alert("请完善文件分享对象的信息");
            }
        }
        function GetMultipleDepartment(){
            var academy = $("#file_academy_select").val();
            var data_return = '';
            for (var i = 0; i < academy.length - 1; i++){
                data_return += academy[i];
                data_return += ',';

            }
            data_return += academy[i];
            $.ajax({
                type:'POST',
                data:{'academy': data_return},
                url:{% url 'user:get_department_multiple' %},
                cache: false,
                dataType: 'json',
                success: function(result){
                    console.log(result);
                    var htmlReplace = '<select multiple class="form-control" id="file_department_select">';
                    for (var i in result){
                        htmlReplace += '<option value=' + i + '>' + result[i] + '</option>';
                    }
                    htmlReplace += '</select>';
                    $("#file_department_select").replaceWith(htmlReplace);
                },
                error: function(result){
                    console.log(result);
                }
            });
        }
        function removeDangerInfo(){
            for (var item in file_share_dander_info){
                $("#" + file_share_dander_info[item]).attr("class", "sr-only");
            }
        }
        function fileShareComplete(){
            removeDangerInfo();
            var flag = 1;
            var sex = $("#file_sex_selection").val();
            if (sex == ''){
                $("#file_share_sex").attr("class", "alert alert-danger");
                flag = 0;
            }
            var identity = $("#file_identity_select").val();
            if (identity == ''){
                $("#file_share_identity").attr("class", "alert alert-danger");
                flag = 0;
            }
            var academy = $("#file_academy_select").val();
            if (identity == ''){
                $("#file_share_academy").attr("class", "alert alert-danger");
                flag = 0;
            }
            var department = $("#file_department_select").val();
            if (department == null){
                $("#file_share_department").attr("class", "alert alert-danger");
                flag = 0;
            }
            if (flag == 1) {
                var file_share = sex + ":" + identity + ":" + academy + ":" + department;
                $("#fileAttributeSelect").attr('hidden', 'hidden');
                var form = $("#file_upload_form");
                form.find("#file_upload_btn").attr('type', 'submit');
            }
            else{
                alert("请完善文件共享信息");
            }
            $("#id_share").val(file_share);

    }
    $(document).ready(function(){
        $.ajax({
            type:'POST',
            data: {'info':'721821'},
            url: '{% url 'user:user_info_if_complete_authenticate' %}',
            cache: false,
            dataType: 'html',
            success: function(result){
                if (result == '1'){
                    alert("请完善用户信息");
                    $("#complete_user_info").modal('show');
                }
            },
            error: function(result){
                alert("网络并不稳定");
            }
        });
        return false;
    });
    </script>
{% endblock %}
{% block title %}文件上传{% endblock %}
{% block intert-hook %}
    <div class="overview">
       <h1 class="page-header">文件上传</h1>
       <p>文件上传</p>
        <div class="file-upload">
            <form enctype="multipart/form-data" id="file_upload_form" method="post">
                {% csrf_token %}
                <p><label for="id_file">File:</label> <input id="id_file" name="file" type="file" /></p>
                <p>
                    <label for="id_share">Share:</label> <input id="id_share" maxlength="400" name="share" type="text" readonly="readonly" />
                    <p>
                        <label for="id_share_type">文件共享:</label>
                            <select id="id_share_type" name="share_type" onchange="set_file_share_object()">
                                <option value="" selected="selected">选择文件共享类型</option>
                                <option value="3">私人</option>
                                <option value="1">公开</option>
                                <option value="2">可共享</option>
                            </select>
                    </p>

                </p>
                <button class="btn btn-info" id="file_upload_btn" type="submit" onclick="alert_complete_user_info(this)">上传</button>
            </form>
        </div>
        <form class="form-horizontal" id="fileAttributeSelect" hidden="hidden">
            <h3>选择文件分享的对象</h3>
            <br/>
            <div class="form-group">
                <div class="col-sm-9">
                    <label>选择文件可共享对象的性别</label>
                    <div class="sr-only" id="file_share_sex" role="alert"><p>请选择性别</p></div>
                    <select class="form-control" id="file_sex_selection">
{#                        <option value selected="selected">选择文件可共享对象的性别</option>#}
                        <option value="0">全选</option>
                        <option value="1">女</option>
                        <option value="2">男</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-9">
                    <label>选择文件可共享对象的身份</label>
                    <div class="sr-only" id="file_share_identity" role="alert"><p>请选择身份</p></div>
                    <select multiple class="form-control" id="file_identity_select">
{#                        <option value selected="selected">选择文件可共享对象的身份</option>#}
                        <option value="4">本科生</option>
                        <option value="5">研究生</option>
                        <option value="6">教师</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-9">
                    <label>选择文件可共享对象的所在学院</label>
                <div class="sr-only" id="file_share_academy" role="alert"><p>请选择学院</p></div>
                    <select multiple class="form-control" id="file_academy_select">
                        {% for academy in academys %}
                            <option value="{{ academy.id }}">{{ academy.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button class="btn btn-info" type="button" onclick="GetMultipleDepartment()">获得选择学院的专业</button>
            <div class="form-group">
                <div class="col-xs-9">
                    <label>选择文件可共享对象的所在系</label>
                    <div class="sr-only" id="file_share_department" role="alert"><p>请选择所在系</p></div>
                    <select multiple class="form-control" id="file_department_select">

                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-9">
                    <button type="button" class="btn btn-info" id="file_share_complete" onclick="fileShareComplete()">确定文件共享对象</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}